name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Composer dependencies
        run: composer install
      - name: Install npm dependencies
        run: npm i
        
      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          
      - run: cat .env
        
      - name: Run phpunit tests
        run: vendor/bin/phpunit tests
#       - name: Run jest tests
#         run: jest resources/js
        
      - name: Build js
        run: npm run prod
      
      - name: Compress project
        run: zip -r project.zip . -x '*node-modules*'
      - run: ls *.zip
        
      - name: Copy code to server
        uses: appleboy/scp-action@master
        with:
          source: project.zip
          target: cederlink.johngachihi.com/public_html/IAP_CAT2
          host: johngachihi.com
          username: johndpwi
          port: 21098
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          
      - name: Extract project on server
        uses: appleboy/ssh-action@master
        with:
          host: johngachihi.com
          username: johndpwi
          port: 21098
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd cederlink.johngachihi.com/public_html/IAP_CAT2
            unzip project.zip
        
#     - uses: actions/checkout@v1
#     - name: Install npm dependencies
#       run: npm install
#     - name: Install composer dependencies
#       run: composer install
#     - name: Create .env file
#       run: cp .env.example .env
#     - name: Generate Laravel key
#       run: php artisan key:generate
#     - name: Run test
#       run: vendor/bin/phpunit
#     - name: Setup SSH key
#       run: echo ${{secrets.SSH_PRIVATE_KEY}} >>  ~/.ssh/id_rsa
#     - name: Print id_rsa  
#       run: cat ~/.ssh/id_rsa
#     - name: Install Deployer
#       run: |
#         curl -LO https://deployer.org/deployer.phar
#         sudo mv deployer.phar /usr/local/bin/dep
#         sudo chmod +x /usr/local/bin/dep
#     - name: Deploy
#       run: dep pwd
    
