name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: composer install
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: johngachihi.com
          username: johndpwi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 21098
          script: |
            cd cederlink.johngachihi.com/public_html
            echo "A la mode" >> ble.txt
            
#     - uses: actions/checkout@v1
#     - name: Install npm dependencies
#       run: npm install
#     - name: Install composer dependencies
#       run: composer install
#     - name: Create .env file
#       run: cp .env.example .env
#     - name: Generate Laravel key
#       run: php artisan key:generate
#     - name: Run test
#       run: vendor/bin/phpunit
#     - name: Setup SSH key
#       run: echo ${{secrets.SSH_PRIVATE_KEY}} >>  ~/.ssh/id_rsa
#     - name: Print id_rsa  
#       run: cat ~/.ssh/id_rsa
#     - name: Install Deployer
#       run: |
#         curl -LO https://deployer.org/deployer.phar
#         sudo mv deployer.phar /usr/local/bin/dep
#         sudo chmod +x /usr/local/bin/dep
#     - name: Deploy
#       run: dep pwd
    
